### ISSUE TITLE
(tweak) Please consider adding a license

### ISSUE THREAD

**Issue by dfgHiatus** [Physics-Dude/Phys-Index-EyetrackVR-HW#4]
I am thinking of using the Babble 3D models for an assembly animation. I wanted to confirm this was suitable with you for our use case.

**Comment by Physics-Dude** [comment]
Sounds cool to me! Go for it.
I'll go ahead and add the MIT License unless someone has an alternate suggestion.

**Comment by Physics-Dude** [comment]
added https://github.com/Physics-Dude/Phys-Index-EyetrackVR-HW/blob/main/LICENSE
