### ISSUE TITLE
USB Hub Requirement confusing cased me to get the wrong one

### ISSUE THREAD

**Issue by AAMBIENTT** [Physics-Dude/Phys-Index-EyetrackVR-HW#6]
Would like to point out the usb hub in the image of the guide is one you DONT want us to buy. That has the LED and is too short for all of the adapters. Please use an image like this one to tell us what to look for 
Wrong: https://www.amazon.com/Aluminium-Splitter-Expander-Console-Keyborad/dp/B0BJZ753D9
Right: https://www.amazon.com/YaimhSound-Extender-Splitter-Extension-Keyborad/dp/B0BXJ21DXZ

**Comment by Physics-Dude** [comment]
You are right, the listing has changed. I will update the writeup now.
(i will also strike out the old one just in case it is a temporary amazon change.)

**Comment by AAMBIENTT** [comment]
could you please update the image as well, as that model in the image is the one i purchased and it was very wrong.

**Comment by Physics-Dude** [comment]
done! there is also a gum stick frame variant that should allow for the flipped hub design as well.

**Comment by AAMBIENTT** [comment]
you're awesome! Thank you! You should make a discord so we could connect on this if youd like
